apiVersion: v1
kind: Secret
metadata:
  name: lake-s3-credentials
stringData:
  KEY_ID: AKIA...
  SECRET: ...
---
apiVersion: database.serenedb.com/v1alpha1
kind: ServerSecret
metadata:
  name: lake
spec:
  cluster:
    name: serenedb-sample
  type: s3
  scope: s3://my-lake/
  options:
    REGION: eu-central-1
  valuesFrom:
    name: lake-s3-credentials
