resources:
- database_v1alpha1_serenedb.yaml
- database_v1alpha1_serenedb_tls.yaml
- database_v1alpha1_database.yaml
- database_v1alpha1_databaserole.yaml
- database_v1alpha1_serversecret.yaml
- database_v1alpha1_backup.yaml
- database_v1alpha1_scheduledbackup.yaml
- database_v1alpha1_serenedb_restore.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
